version: '3.9'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - app.env
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - postgres.env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: